In [26]:
#Question One

In [28]:
import numpy as np

# create a vector of length 5 filled with arbitrary integers from 0 to 10
vector = np.random.randint(0, 11, size=5)

print(vector)

[9 1 5 1 1]


In [30]:
#Question Two

In [32]:
# create a vector with values ranging from 15 to 55
vector = np.arange(15, 56)

# print all values except the first and last
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [34]:
#Question Three

In [36]:
# create a random array with 1000 elements
arr = np.random.rand(1000)

# compute the average, variance, standard deviation of the array elements
avg = np.mean(arr)
var = np.var(arr)
std_dev = np.std(arr)

print("Average:", avg)
print("Variance:", var)
print("Standard Deviation:", std_dev)

Average: 0.511485998633109
Variance: 0.08407184974210062
Standard Deviation: 0.28995146101046054


In [38]:
#Question Four

In [40]:
# create a 3x3 array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# calculate cumulative sum of the elements along axis 0 (sum over rows)
sum_axis_0 = np.cumsum(arr, axis=0)

# calculate cumulative sum of the elements along axis 1 (sum over columns)
sum_axis_1 = np.cumsum(arr, axis=1)

# print the results
print("Cumulative sum over rows for each of the 3 columns:\n", sum_axis_0)
print("Cumulative sum over columns for each of the 2 rows:\n", sum_axis_1)

Cumulative sum over rows for each of the 3 columns:
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
Cumulative sum over columns for each of the 2 rows:
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [42]:
#Question Five

In [44]:
# create two matrices
mat1 = np.array([[1, 0], [0, 1]])
mat2 = np.array([[1, 2], [3, 4]])

# multiply the matrices
result = np.dot(mat1, mat2)

# print the result
print(result)

[[1 2]
 [3 4]]
